name: packer
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: packer validate packer.json
        uses: docker://hashicorp/packer:1.5.1
        with:
          args: validate packer.json
      - name: packer build packer.json
        uses: docker://hashicorp/packer:1.5.1
        with:
          args: build packer.json
        env:
          GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
          GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
