name: packer
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: packer validate packer.json
        uses: docker://dchambon/packer-ansible:latest
        with:
          args: validate packer.json
      - name: packer build packer.json
        uses: docker://dchambon/packer-ansible:latest
        with:
          args: build -force packer.json
        env:
          GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
          GKE_ACCOUNT: ${{ secrets.GKE_ACCOUNT }}
          APP_USER_PASSWORD: ${{ secrets.APP_USER_PASSWORD }}
